name: Build APK with Buildozer
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build APK with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/kivy/buildozer:master
          options: -v ${{ github.workspace }}:/home/user/hostpython -w /home/user/hostpython
          run: |
            buildozer android debug
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
           name: package-apk
           path: bin/*.apk
